import { ssrRenderAttrs, ssrRenderAttr, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const _imports_0 = "/my-blog/assets/111.BJDcWzHq.png";
const _imports_1 = "/my-blog/assets/112.BIEg6hZB.png";
const _imports_2 = "/my-blog/assets/113.-yanTC5s.png";
const _imports_3 = "/my-blog/assets/114.DTqCHL9u.png";
const _imports_4 = "/my-blog/assets/115.BCJYDpwq.png";
const _imports_5 = "/my-blog/assets/116.BZ-jcQmg.png";
const _imports_6 = "/my-blog/assets/117.CO_-InHl.png";
const _imports_7 = "/my-blog/assets/118.Bzeif-Y1.png";
const _imports_8 = "/my-blog/assets/119.CO2QQj_C.png";
const _imports_9 = "/my-blog/assets/120.D-MiVPOF.png";
const _imports_10 = "/my-blog/assets/121.BYPHjLNo.png";
const __pageData = JSON.parse('{"title":"NestJS 教程 21：日志体系与 AOP 日志落地","description":"合并日志处理与面向切面日志处理，完整搭建 Nest 内置日志、Winston、自定义日志器与中间件/拦截器/过滤器日志链路。","frontmatter":{"title":"NestJS 教程 21：日志体系与 AOP 日志落地","date":"2026-03-10T00:00:00.000Z","description":"合并日志处理与面向切面日志处理，完整搭建 Nest 内置日志、Winston、自定义日志器与中间件/拦截器/过滤器日志链路。"},"headers":[],"relativePath":"tutorials/nestjs/nestjs-tutorial-21-logging-and-aop.md","filePath":"tutorials/nestjs/nestjs-tutorial-21-logging-and-aop.md"}');
const _sfc_main = { name: "tutorials/nestjs/nestjs-tutorial-21-logging-and-aop.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h2 id="为什么日志体系重要" tabindex="-1">为什么日志体系重要 <a class="header-anchor" href="#为什么日志体系重要" aria-label="Permalink to &quot;为什么日志体系重要&quot;">​</a></h2><p>开发环境调试相对容易，但生产环境通常无法直接附加调试器，日志就是定位问题和回溯行为的核心数据源。一个可用的日志体系至少要满足：</p><ul><li>可观测：知道请求做了什么、在哪失败</li><li>可检索：按级别、按时间、按模块快速定位</li><li>可维护：日志代码不污染业务逻辑</li></ul><h2 id="_1-nest-内置-logger" tabindex="-1">1. Nest 内置 Logger <a class="header-anchor" href="#_1-nest-内置-logger" aria-label="Permalink to &quot;1. Nest 内置 Logger&quot;">​</a></h2><p>Nest 默认开启日志，应用启动即可看到格式化输出：</p><p><img${ssrRenderAttr("src", _imports_0)} alt="Nest 启动日志"></p><p>你也可以按级别控制输出：</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> app</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> NestFactory.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">create</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(AppModule, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  logger: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;error&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;warn&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">})</span></span></code></pre></div><p>在业务中建议用 <code>Logger</code> 替换 <code>console.log</code>，并带上上下文。</p><p><img${ssrRenderAttr("src", _imports_1)} alt="Service 中输出日志"></p><h2 id="_2-自定义日志器模块" tabindex="-1">2. 自定义日志器模块 <a class="header-anchor" href="#_2-自定义日志器模块" aria-label="Permalink to &quot;2. 自定义日志器模块&quot;">​</a></h2><p>可以创建 <code>LoggerModule</code> 并实现 <code>MyLogger</code>（继承 <code>ConsoleLogger</code> 或实现 <code>LoggerService</code>），统一日志格式，再通过 DI 注入使用。</p><p>在 <code>main.ts</code> 中切换日志器：</p><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> app</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> NestFactory.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">create</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(AppModule, { bufferLogs: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">app.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">useLogger</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(app.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">get</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(MyLogger))</span></span></code></pre></div><p><code>bufferLogs: true</code> 表示先缓存启动日志，待自定义 logger 准备好后统一输出。</p><h2 id="_3-第三方日志器-winston" tabindex="-1">3. 第三方日志器 Winston <a class="header-anchor" href="#_3-第三方日志器-winston" aria-label="Permalink to &quot;3. 第三方日志器 Winston&quot;">​</a></h2><p>生产环境通常会接入 Winston：</p><div class="language-shell vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">shell</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> add</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> winston</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> winston-daily-rotate-file</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dayjs</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -S</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> add</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> chalk@4</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -S</span></span></code></pre></div><p><img${ssrRenderAttr("src", _imports_2)} alt="安装依赖"></p><p>通过 Winston 可以实现：</p><ul><li>多级别日志（error/warn/info/debug）</li><li>控制台彩色输出</li><li>按天滚动文件</li><li>保留周期清理</li></ul><p>配置后控制台输出效果：</p><p><img${ssrRenderAttr("src", _imports_3)} alt="Winston 启动输出"></p><p><img${ssrRenderAttr("src", _imports_4)} alt="接口请求日志输出"></p><p>优化格式后：</p><p><img${ssrRenderAttr("src", _imports_5)} alt="彩色格式化日志"></p><p>同时落盘：</p><p><img${ssrRenderAttr("src", _imports_6)} alt="日志文件落盘"></p><h2 id="_4-面向切面的日志处理-aop-思路" tabindex="-1">4. 面向切面的日志处理（AOP 思路） <a class="header-anchor" href="#_4-面向切面的日志处理-aop-思路" aria-label="Permalink to &quot;4. 面向切面的日志处理（AOP 思路）&quot;">​</a></h2><p>手工在每个路由写日志效率低，建议用全局切面能力统一采集。</p><h3 id="_4-1-中间件-采集请求入口" tabindex="-1">4.1 中间件：采集请求入口 <a class="header-anchor" href="#_4-1-中间件-采集请求入口" aria-label="Permalink to &quot;4.1 中间件：采集请求入口&quot;">​</a></h3><p><code>LoggerMiddleware</code> 适合记录请求信息：</p><ul><li>URL、Method、IP</li><li>Params / Query / Body</li><li>状态码分级写入 info/warn/error</li></ul><p>应用到全局路由后：</p><p><img${ssrRenderAttr("src", _imports_7)} alt="中间件日志输出"></p><h3 id="_4-2-拦截器-采集响应结果" tabindex="-1">4.2 拦截器：采集响应结果 <a class="header-anchor" href="#_4-2-拦截器-采集响应结果" aria-label="Permalink to &quot;4.2 拦截器：采集响应结果&quot;">​</a></h3><p><code>ResponseInterceptor</code> 在 <code>next.handle()</code> 后记录响应数据，适合统计成功响应与返回结构。</p><p><img${ssrRenderAttr("src", _imports_8)} alt="拦截器日志输出"></p><h3 id="_4-3-过滤器-采集异常出口" tabindex="-1">4.3 过滤器：采集异常出口 <a class="header-anchor" href="#_4-3-过滤器-采集异常出口" aria-label="Permalink to &quot;4.3 过滤器：采集异常出口&quot;">​</a></h3><p><code>HttpExceptionFilter</code> 统一捕获异常并记录错误日志，同时返回标准化错误响应。</p><p><img${ssrRenderAttr("src", _imports_9)} alt="异常响应示例"></p><p><img${ssrRenderAttr("src", _imports_10)} alt="后台异常日志"></p><h2 id="小结" tabindex="-1">小结 <a class="header-anchor" href="#小结" aria-label="Permalink to &quot;小结&quot;">​</a></h2><p>这一篇把 Nest 日志从“能打印”提升到“可运营”：</p><ul><li>基础层：内置 Logger + 自定义 Logger</li><li>持久层：Winston + 日志轮转</li><li>切面层：中间件（请求）+ 拦截器（响应）+ 过滤器（异常）</li></ul><p>最终目标是统一格式、统一入口、统一异常出口，让日志真正可用于生产排障和审计分析。</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("tutorials/nestjs/nestjs-tutorial-21-logging-and-aop.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const nestjsTutorial21LoggingAndAop = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  nestjsTutorial21LoggingAndAop as default
};
